stages:
  - clone
  - build
  - deploy

clone:
  image: alpine
  stage: clone
  script:
    - git clone https://$GIT_USERNAME:$GIT_PASSWORD@bitbucket.org/raikjakschis/hamster_widgets.git
    - cd hamster_widgets && git checkout develop
  artifacts:
    - hamster_widgets/**

build:
  image: cirrusci/flutter:stable
  stage: build
  script:
    - flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
    - flutter build web -t lib/main_development.dart --release --web-renderer html
  artifacts:
    - build/web/**

#deploy:
#  image: atlassian/pipelines-awscli
#  script:
#    - pipe: atlassian/aws-s3-deploy:1.1.0
#  variables:
#    AWS_ACCESS_KEY_ID: $AWS_KEY
#    AWS_SECRET_ACCESS_KEY: $AWS_SECRET
#    AWS_DEFAULT_REGION: $AWS_REGION
#    S3_BUCKET: 'www.hamster.business'
#    LOCAL_PATH: 'build/web/'
#    ACL: 'public-read'
