stages:
  - clone
  - build
  - deploy

clone:
  image: bitnami/git
  stage: clone
  tags:
    - docker
  script:
    - git clone https://$GIT_USERNAME:$GIT_PASSWORD@bitbucket.org/raikjakschis/hamster_widgets.git
    - cd hamster_widgets && git checkout develop
  artifacts:
    paths:
      - hamster_widgets/**

build:
  image: cirrusci/flutter:stable
  stage: build
  tags:
    - docker
  script:
    - flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
    - flutter build web -t lib/main_development.dart --release --web-renderer html
  artifacts:
    paths:
      - build/web/**

deploy:
  image: atlassian/default-image:2
  stage: deploy
  tags:
    - docker
  script:
    - apt-get update -y && apt-get install -y curl unzip groff jq bc
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install

  variables:
    AWS_ACCESS_KEY_ID: $AWS_KEY
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET
    AWS_DEFAULT_REGION: $AWS_REGION
    S3_BUCKET: 'www.hamster.business'
    LOCAL_PATH: 'build/web/'
    ACL: 'public-read'
