stages:
  - clone
  - analyze
  - build
  - deploy

variables:
  LOCAL_PATH: 'build/web/'

clone:
  image: bitnami/git
  stage: clone
  tags:
    - hamster
  script:
    - git clone https://$GIT_USERNAME:$GIT_PASSWORD@bitbucket.org/raikjakschis/hamster_widgets.git
    - cd hamster_widgets && git checkout develop
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    paths:
      - hamster_widgets/**

analyze:
  image: cirrusci/flutter:stable
  stage: analyze
  tags:
    - hamster
  script:
    - dart analyze
  allow_failure: true
  rules:
    - if: ('$CI_PIPELINE_SOURCE == "merge_request_event"' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")

build-dev:
  image: cirrusci/flutter:stable
  stage: build
  tags:
    - hamster
  script:
    - sed -i 's/git:/path:/g' pubspec.yaml
    - sed -i 's/path:/& \.\/hamster_widgets/' pubspec.yaml
    - sed -i '/url:/d' pubspec.yaml
    - sed -i '/ref:/d' pubspec.yaml
    - flutter pub add intl_utils
    - dart pub global activate intl_utils 2.6.1
    - flutter pub global run intl_utils:generate
    - flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
    - flutter build web -t lib/main_development.dart --release --web-renderer html --dart-define="base_url=$DEV_BASE_URL"
  rules:
    - if: ('$CI_PIPELINE_SOURCE == "merge_request_event"' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")
  artifacts:
    paths:
      - build/web/**

build-stage:
  image: cirrusci/flutter:stable
  stage: build
  tags:
    - hamster
  script:
    - sed -i 's/git:/path:/g' pubspec.yaml
    - sed -i 's/path:/& \.\/hamster_widgets/' pubspec.yaml
    - sed -i '/url:/d' pubspec.yaml
    - sed -i '/ref:/d' pubspec.yaml
    - flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
    - flutter build web -t lib/main_development.dart --release --web-renderer html --dart-define="base_url=$STAGE_BASE_URL"
  rules:
    - if: ('$CI_PIPELINE_SOURCE == "merge_request_event"' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test")
  artifacts:
    paths:
      - build/web/**

deploy-dev:
  image: atlassian/default-image:2
  stage: deploy
  environment: dev
  tags:
    - hamster
  script:
    - apt-get update -y && apt-get install -y curl unzip groff jq bc
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync $LOCAL_PATH "s3://$CI_ENVIRONMENT_NAME$S3_BUCKET_NAME" --acl public-read --delete
    - aws cloudfront create-invalidation --distribution-id $DEV_DISTRIBUTION_ID --paths '/*'
  rules:
    - if: ('$CI_PIPELINE_SOURCE == "merge_request_event"' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop")

deploy-stage:
  image: atlassian/default-image:2
  stage: deploy
  environment: test
  tags:
    - hamster
  script:
    - apt-get update -y && apt-get install -y curl unzip groff jq bc
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync $LOCAL_PATH "s3://$CI_ENVIRONMENT_NAME$S3_BUCKET_NAME" --acl public-read --delete
    - aws cloudfront create-invalidation --distribution-id $STAGE_DISTRIBUTION_ID --paths '/*'
  rules:
    - if: ('$CI_PIPELINE_SOURCE == "merge_request_event"' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test")



