include: package:very_good_analysis/analysis_options.2.4.0.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: false
    sort_constructors_first: false
    prefer_const_literals_to_create_immutables: false

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.config.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/generated/**.dart'
  errors:
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

