name: business_terminal
description: Hamster Systems Business Terminal
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management:
  flutter_bloc: ^8.0.1
  freezed_annotation: ^0.14.2
  equatable: ^2.0.3

  # DI
  injectable: ^1.5.0

  # Navigation
  routemaster: ^1.0.0

  # Tools:
  intl: ^0.17.0
  reactive_forms: ^12.0.0

  # Network:
  dio: 4.0.6
  retrofit:
  pretty_dio_logger: ^1.1.1

  # Tools:
  get_it: ^7.2.0
  logger: ^1.1.0
  dart_extensions: ^2.2.0
  dartz: ^0.10.1

  # UI:
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  black_hole_flutter: ^0.3.5
  dropdown_button2: ^1.4.0
  animated_custom_dropdown: ^1.2.0
  hamster_widgets:
    git:
      url: https://bitbucket.org/raikjakschis/hamster_widgets
      ref: develop
  cached_network_image:
  loader_overlay: ^2.0.6
  pinput: ^2.2.7


dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
  retrofit_generator:

  build_runner: ^2.0.1
  json_serializable: ^6.1.5
  freezed: ^0.14.2
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/flags/
