name: business_terminal
description: Hamster Systems Business Terminal
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

    # State management:
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

    # Tools:
  intl: ^0.17.0
  reactive_forms: ^12.0.0

    # UI:
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  black_hole_flutter: ^0.3.5


dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
